# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaferpayResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('payload', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SaferpayTransaction',
            fields=[
                ('token', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('transaction_id', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('AUTHORIZED', 'AUTHORIZED'), ('CAPTURED', 'CAPTURED'), ('CANCELD', 'CANCELD')], default='NEW', max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=32, null=True)),
                ('error_message', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddField(
            model_name='saferpayresponse',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saferpay.SaferpayTransaction'),
        ),
    ]
