# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferpaytransaction',
            name='language_code',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
