# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferpay', '0002_saferpaytransaction_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferpayresponse',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
    ]
