# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferpay', '0004_auto_20180815_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferpaytransaction',
            name='has_notify',
            field=models.BooleanField(default=False),
        ),
    ]
