# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferpay', '0005_saferpaytransaction_has_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferpaytransaction',
            name='notify_token',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
